-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE items PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE items (
    id NUMBER(10) PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

CREATE OR REPLACE PROCEDURE noop AS
BEGIN
    NULL;
END;
/

EXIT SUCCESS
