# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "otel-conformance-scenario"
version = "0.1.0"
workspace = "../../../scenarios/http/rust"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true
