pluginManagement {
    includeBuild("../../../tools/java/gradle-plugins")
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "http-java-conformance"

include("akka-http:scenarios")
include("akka-http:opentelemetry-javaagent")
include("apache-httpasyncclient:scenarios")
include("apache-httpasyncclient:opentelemetry-javaagent")
include("apache-httpclient:scenarios")
include("apache-httpclient:scenarios-4.3")
include("apache-httpclient:opentelemetry-javaagent")
include("apache-httpclient:opentelemetry-library-4.3")
include("apache-httpclient:opentelemetry-library-5.2")
include("armeria:scenarios")
include("armeria:opentelemetry-javaagent")
include("armeria:opentelemetry-library")
include("async-http-client:scenarios")
include("async-http-client:opentelemetry-javaagent")
include("grizzly:scenarios")
include("grizzly:opentelemetry-javaagent")
include("helidon:scenarios")
include("helidon:opentelemetry-javaagent")
include("helidon:opentelemetry-library")
include("http-url-connection:scenarios")
include("http-url-connection:opentelemetry-javaagent")
include("java-http-client:scenarios")
include("java-http-client:opentelemetry-javaagent")
include("java-http-client:opentelemetry-library")
include("java-http-server:scenarios")
include("java-http-server:opentelemetry-javaagent")
include("java-http-server:opentelemetry-library")
include("jetty-httpclient:scenarios")
include("jetty-httpclient:scenarios-9.2")
include("jetty-httpclient:opentelemetry-javaagent")
include("jetty-httpclient:opentelemetry-library-9.2")
include("jetty-httpclient:opentelemetry-library-12.0")
include("jodd-http:scenarios")
include("jodd-http:opentelemetry-javaagent")
include("ktor:scenarios-1.0")
include("ktor:opentelemetry-library-1.0")
include("ktor:scenarios-2.0")
include("ktor:opentelemetry-library-2.0")
include("ktor:scenarios-3.0")
include("ktor:opentelemetry-library-3.0")
include("netty:scenarios")
include("netty:opentelemetry-javaagent")
include("netty:opentelemetry-library")
include("okhttp:scenarios")
include("okhttp:opentelemetry-javaagent")
include("okhttp:opentelemetry-library")
include("pekko-http:scenarios")
include("pekko-http:opentelemetry-javaagent")
include("ratpack:scenarios")
include("ratpack:opentelemetry-javaagent")
include("ratpack:opentelemetry-library")
include("reactor-netty:scenarios")
include("reactor-netty:opentelemetry-javaagent")
include("restlet:scenarios")
include("restlet:scenarios-1.1")
include("restlet:opentelemetry-javaagent")
include("restlet:opentelemetry-library-1.1")
include("restlet:opentelemetry-library-2.0")
include("servlet:scenarios")
include("servlet:scenarios-3.0")
include("servlet:opentelemetry-javaagent")
include("servlet:opentelemetry-library-3.0")
include("servlet:opentelemetry-library-5.0")
include("spring-web:scenarios")
include("spring-web:opentelemetry-library")
include("spring-webflux:scenarios")
include("spring-webflux:opentelemetry-javaagent")
include("spring-webflux:opentelemetry-library")
include("spring-webmvc:scenarios-5.3")
include("spring-webmvc:opentelemetry-library-5.3")
include("spring-webmvc:scenarios-6.0")
include("spring-webmvc:opentelemetry-library-6.0")
include("tomcat:scenarios")
include("tomcat:opentelemetry-javaagent")
include("undertow:scenarios")
include("undertow:opentelemetry-javaagent")
include("vertx-http-client:scenarios")
include("vertx-http-client:opentelemetry-javaagent")

fun shared(name: String, directory: String) {
    include(name)
    project(":$name").projectDir = file(directory)
}

shared("scenario-support", "../../../tools/java/scenario-support")
shared("scenario-sdk", "../../../tools/java/scenario-sdk")
shared("http-test-client", "../../../tools/http/test-client/java")
