[project]
name = "pyramid-opentelemetry-conformance-server"
version = "0.0.0"
requires-python = ">=3.12"
dependencies = [
    "pyramid==2.1",
    "opentelemetry-api==1.44.0",
    "opentelemetry-sdk==1.44.0",
    "opentelemetry-exporter-otlp-proto-grpc==1.44.0",
    "opentelemetry-instrumentation-pyramid==0.65b0",
    "otel-conformance-python",
    "otel-http-test-client",
]

[tool.uv.sources]
otel-conformance-python = { path = "../../../../../../tools/python", editable = true }
otel-http-test-client = { path = "../../../../../../tools/http/test-client/python", editable = true }

[tool.uv]
package = false
