# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

require "rake/testtask"

Rake::TestTask.new do |task|
  task.libs << "lib"
  task.pattern = "test/**/*_test.rb"
end

task default: :test
